# config.yaml
environment:
  name: "myapp_env"
  python_version: "3.13"
  
dependencies:
  - "requests>=2.2s5.0"
  - "numpy>=1.20.0"
  - "pandas>=1.3.0"
  
scripts:
  setup: "python setup.py install"
  test: "pytest tests/"
  run: "python main.py"